export const DEFAULT_TITLE = `Lorem Ipsum`;

export const DEFAULT_TEXT = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dictum elit varius viverra gravida. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In a ligula nec felis ornare elementum. Suspendisse potenti. Suspendisse pellentesque placerat nibh, at fermentum risus posuere tempus. Donec elementum lectus eu ante mattis finibus. Cras rhoncus tellus vel lacus faucibus hendrerit. Vestibulum convallis, metus vel consequat venenatis, nulla nisl scelerisque neque, sit amet finibus turpis turpis ut nisl. Quisque ut aliquet dui, interdum luctus neque. Curabitur ac cursus sem. Cras sed nisl ut ipsum condimentum volutpat. Phasellus a diam sit amet leo sagittis ultrices vitae vitae orci. Phasellus rutrum, eros quis aliquam vestibulum, purus orci porttitor sapien, sit amet tempor ante urna non urna. Donec nec lorem ut magna congue rhoncus ac a justo.

Vivamus maximus enim dignissim, laoreet augue a, efficitur ex. Maecenas lacinia dapibus sapien, sed euismod urna euismod nec. Phasellus non justo non ex dignissim viverra a sit amet enim. Nunc nisi lorem, imperdiet sed blandit sed, aliquam ut sapien. Proin nec iaculis mi. Nulla eget nulla ultrices, suscipit eros vel, finibus elit. Nunc sagittis laoreet dui, sit amet dictum lacus fermentum in. Proin quis leo felis. Nulla ante velit, dignissim vitae nisl id, mollis malesuada diam.

In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam ac neque sapien. Phasellus dui mi, bibendum sit amet quam sed, faucibus feugiat urna. Quisque a lectus euismod urna dapibus maximus nec nec sapien. Nunc sagittis facilisis sapien in consequat. Curabitur varius sit amet sem at gravida. Sed ultricies vitae mi et bibendum. Aliquam velit ligula, fermentum eget tellus ut, volutpat sodales mi. Vivamus accumsan at nunc a maximus. Nulla rutrum imperdiet ex consequat volutpat. Etiam suscipit lacus et dui imperdiet, a sodales quam laoreet. Curabitur ut metus at lorem congue auctor. In orci odio, tempus sed vulputate a, tempus eget mi. Integer venenatis erat lectus, sit amet semper massa vulputate sed.

Pellentesque aliquam ipsum purus, id ullamcorper sapien pretium et. Nulla facilisi. Mauris non dolor nisl. Sed ut velit ac est ullamcorper ullamcorper vitae at diam. Proin sit amet dolor accumsan, accumsan dolor aliquet, vehicula dui. Cras tincidunt dolor est, a efficitur quam pulvinar finibus. Maecenas tincidunt tincidunt tellus ullamcorper porttitor.

Vivamus tristique velit sit amet interdum sollicitudin. Morbi elementum accumsan quam, in volutpat massa scelerisque et. Integer et ex vel ante porta lobortis id non nisi. Mauris in pulvinar dolor. Sed condimentum lorem a iaculis vulputate. Morbi sed mauris nisl. Morbi dolor justo, accumsan vitae rhoncus eget, laoreet eu urna.`;

export const DEFAULT_TERMS = ['lorem', 'amet', 'dui'];

export const TEMPLATE_REGEX = /\{\{([A-Za-z0-9]+(-[A-Za-z0-9]+)+)\}\}/g;
